device: cuda:0
TARGET_PADDING: 0
LESION: lesion2
model_path: models/remaster_1.pth
EPOCHS: 2000
CHANNEL_N: 16
CELL_FIRE_RATE: 0.5
BATCH_SIZE: 8

SCALE_GROWTH: 1
SCALE_GROWTH_SYN: 1

lr: 2e-3
betas_0: 0.5
betas_1: 0.5

lr_gamma: 0.9999

ITER_GROW: 60
ITER_SAVE: 30

save_reconstruction: False

wandb:
  save: True
  name: cell_auto

SAVE_NUMPY: False

data:
  data_folder: /content/drive/MyDrive/Datasets/covid19/COVID-19-20_v2/Train
  path_single_lesions: /content/drive/MyDrive/Datasets/covid19/COVID-19-20/individual_lesions/
  path_texture: /content/drive/My Drive/Datasets/covid19/results/cea_synthesis/patient0/
  SCAN_NAME: volume-covid19-A-0014
  SLICE: 34
  BATCH_SIZE: 1

loop:
  SKIP_LESIONS: -1
  ONLY_ONE_SLICE: True
  TRESH_PLOT: 20
  ONLY_ONE_LESION: 0

seed:
  SEED_VALUE: 0.19
  